name: Update Static Files

on:
  push:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  UpdateUnicodeData:
    name: Update Unicode Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run the Unicode Extraction script
        run: node ./scripts/extract-unicode-data.mjs 
      - name: Commit any changes and create a pull request
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b update-unicode/$(date +%F-%H-%M);
            git commit -sam "refactor: update unicode data";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
            gh pr create -t "refactor: update unicode data" -b "*bleep bloop* I updated the unicode data file" -B main;
          fi

  UpdateTimezone:
    name: Update Timezone Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run the Timezone Extraction script
        run: node ./scripts/extract-timezone-data.mjs
      - name: Commit any changes and create a pull request
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b update-timezones/$(date +%F-%H-%M);
            git commit -sam "refactor: update timezones data";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
            gh pr create -t "refactor: update timezones data" -b "*bleep bloop* I updated the timezones data file" -B main;
          fi
